platform :ios, "8.0"

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aotian16/SwiftToast.git'

use_frameworks!

pod "SwiftToast", :path => '/Users/tongjin/.cocoapods/repos/SwiftToast/SwiftToast'

target :SwiftToastDemoTests, :exclusive => true do
  # pod 'Kiwi'
end
